name: Deploy

on:
  push:
    branches:
      - prod

env:
  CONTAINER_IMAGE: market
  USER_DIR: /root

jobs:
  frontendtests:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    defaults:
      run:
        working-directory: app

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        run: npm run test

  backendtests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6380:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

    # TODO: deploy
